title: Hanqing Liu's Homepage
page-top-title: Hanqing Liu
top-section-bg-text: Intelligent Science and Technology
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Hanqing Liu 2026-. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/senli1073
license-link:
  text: License
  href: https://github.com/senli1073/senli1073.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Hanqing Liu&ensp;|&ensp;刘汉青
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
